name: Scrape and Commit Outputs

on:
  workflow_dispatch:
    inputs:
      limit_brands:
        description: "限制抓取品牌数量 (默认 2)"
        required: false
        default: "2"
      limit_product_pages:
        description: "每品牌限制产品页数量 (默认 2)"
        required: false
        default: "2"
      limit_details:
        description: "每品牌限制详情数量 (默认 5)"
        required: false
        default: "5"

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system libraries for ddddocr
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0

      - name: Install uv
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync Python dependencies with uv
        shell: bash
        run: |
          uv --version
          uv sync --frozen

      - name: Install Playwright system dependencies and browsers
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true

      - name: Install Chromium for Playwright (Python)
        shell: bash
        run: |
          uv run python -m playwright install chromium

      - name: Warm up ddddocr model cache
        shell: bash
        run: |
          uv run python - <<'PY'
          import ddddocr
          ddddocr.DdddOcr(ocr=True, show_ad=False)
          print("ddddocr ready")
          PY

      - name: Run scraper (main.py)
        shell: bash
        env:
          YANYUE_LIMIT_BRANDS: ${{ github.event.inputs.limit_brands || '2' }}
          YANYUE_LIMIT_PRODUCT_PAGES: ${{ github.event.inputs.limit_product_pages || '2' }}
          YANYUE_LIMIT_DETAILS: ${{ github.event.inputs.limit_details || '5' }}
        run: |
          uv run python main.py

      - name: Commit and push output directories
        if: always()
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add yanyue_tobacco_output yanyue_hnb_output yanyue_e_output || true
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "chore: update scraped outputs from CI [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi